//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioWeb.ServicioCalculo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCalculo.ITrabajo")]
    public interface ITrabajo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrabajo/ObtenerModulo", ReplyAction="http://tempuri.org/ITrabajo/ObtenerModuloResponse")]
        int ObtenerModulo(int A, int B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrabajo/ObtenerModulo", ReplyAction="http://tempuri.org/ITrabajo/ObtenerModuloResponse")]
        System.Threading.Tasks.Task<int> ObtenerModuloAsync(int A, int B);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrabajoChannel : FormularioWeb.ServicioCalculo.ITrabajo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrabajoClient : System.ServiceModel.ClientBase<FormularioWeb.ServicioCalculo.ITrabajo>, FormularioWeb.ServicioCalculo.ITrabajo {
        
        public TrabajoClient() {
        }
        
        public TrabajoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrabajoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrabajoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrabajoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ObtenerModulo(int A, int B) {
            return base.Channel.ObtenerModulo(A, B);
        }
        
        public System.Threading.Tasks.Task<int> ObtenerModuloAsync(int A, int B) {
            return base.Channel.ObtenerModuloAsync(A, B);
        }
    }
}
